property_questions = {
    "educated at": "Where did {entity} receive their education?",
    "instrument": "What instrument does {entity} play?",
    "place of birth": "Where was {entity} born?",
    "religion or worldview": "What is {entity}'s religious belief or worldview?",
    "child": "Who is {entity}'s child?",
    "member of political party": "Which political party does {entity} belong to?",
    "represented by": "Who represents {entity}?",
    "field of work": "In which field does {entity} work?",
    "occupation": "What does {entity} do for a living?",
    "academic degree": "What academic degree does {entity} hold?",
    "spouse": "Who is {entity} married to?",
    "military branch": "In which branch of the military did {entity} serve?",
    "member of": "Which organization is {entity} a member of?",
    "sibling": "Who is {entity}'s sibling?",
    "manner of death": "How did {entity} pass away?",
    "blood type": "What is {entity}'s blood type?",
    "participant in": "What event did {entity} participate in?",
    "medical condition": "What medical condition does {entity} have?",
    "floruit": "During which period was {entity} most active or influential?",
    "place of burial": "Where is {entity} buried?",
    "influenced by": "Who influenced {entity}?",
    "position played on team / speciality": "What position or specialty does {entity} have on the team?",
    "sexual orientation": "What is {entity}'s sexual orientation?",
    "ancestral home": "Where is {entity}'s ancestral home?",
    "birth name": "What was {entity}'s name at birth?",
    "date of birth": "When was {entity} born?",
    "ethnic group": "What is {entity}'s ethnicity?",
    "notable work": "What is {entity}'s most famous work?",
    "noble title": "What noble title does {entity} hold?",
    "significant event": "What significant event marked {entity}'s life?",
    "cause of death": "What caused {entity}'s death?",
    "date of death": "When did {entity} pass away?",
    "student of": "Who taught {entity}?",
    "father": "Who is {entity}'s father?",
    "residence": "Where does {entity} live?",
    "mother": "Who is {entity}'s mother?",
    "supported sports team": "Which sports team does {entity} support?",
    "family name": "What is {entity}'s family name?",
    "position held": "What position does {entity} hold?",
    "member of sports team": "Which sports team is {entity} a member of?",
    "award received": "What award has {entity} received?",
    "employer": "Who employs {entity}?",
    "sport": "What sport does {entity} play?",
    "work location": "Where does {entity} work?",
    "married name": "What is {entity}'s married name?",
    "place of death": "Where did {entity} pass away?",
    "country of citizenship": "What country is {entity} a citizen of?"
}

entity_name = "Albert Einstein"
question = property_questions["occupation"].format(entity=entity_name)
print(question)